### ISSUE TITLE
getCustomerHistoryRecords error 500

### ISSUE THREAD

**Issue by skillix** [Apollon77/alexa-remote#238]
Error: CSRF Page has no token
node:_http_outgoing:648
throw new ERR_HTTP_HEADERS_SENT('set');
^
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
at new NodeError (node:internal/errors:405:5)
at ServerResponse.setHeader (node:_http_outgoing:648:11)
at ServerResponse.header (/var/www/html/plugins/alexaapiv2/resources/node_modules/express/lib/response.js:794:10)
at ServerResponse.send (/var/www/html/plugins/alexaapiv2/resources/node_modules/express/lib/response.js:174:12)
at ServerResponse.json (/var/www/html/plugins/alexaapiv2/resources/node_modules/express/lib/response.js:278:15)
at /var/www/html/plugins/alexaapiv2/resources/alexaapi.js:603:19
at httpsGet.handleAsText (/var/www/html/plugins/alexaapiv2/resources/node_modules/alexa-remote2/alexa-remote.js:2145:52)
at handleResponse (/var/www/html/plugins/alexaapiv2/resources/node_modules/alexa-remote2/alexa-remote.js:1068:24)
at Gunzip.cb (/var/www/html/plugins/alexaapiv2/resources/node_modules/alexa-remote2/alexa-remote.js:1192:37)
at Gunzip.zlibBufferOnEnd (node:zlib:161:10) {
code: 'ERR_HTTP_HEADERS_SENT'

since around 12:00 p.m.

**Comment by Apollon77** [comment]
Sorry, but what should tell me that? 

Which alexa-remote library version is used? Please provide a full log of alexa-remote

**Comment by skillix** [comment]
```
[08/04/2024 22:03:20][DEBUG] : {API}: historyFull: Error: Activity update is running, please try again later.
################ erreur:
Error: Activity update is running, please try again later.
    at AlexaRemote.getCustomerHistoryRecords (/var/www/html/plugins/alexaapiv2/resources/node_modules/alexa-remote2/alexa-remote.js:2125:41)
    at /var/www/html/plugins/alexaapiv2/resources/alexaapi_test.js:601:8
    at Layer.handle [as handle_request] (/var/www/html/plugins/alexaapiv2/resources/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/html/plugins/alexaapiv2/resources/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/var/www/html/plugins/alexaapiv2/resources/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/var/www/html/plugins/alexaapiv2/resources/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/html/plugins/alexaapiv2/resources/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/var/www/html/plugins/alexaapiv2/resources/node_modules/express/lib/router/index.js:346:12)
    at next (/var/www/html/plugins/alexaapiv2/resources/node_modules/express/lib/router/index.js:280:10)
    at expressInit (/var/www/html/plugins/alexaapiv2/resources/node_modules/express/lib/middleware/init.js:40:5)
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFile (node:fs:2271:5)
    at /var/www/html/plugins/alexaapiv2/resources/alexaapi_test.js:607:6
    at AlexaRemote.getCustomerHistoryRecords (/var/www/html/plugins/alexaapiv2/resources/node_modules/alexa-remote2/alexa-remote.js:2125:32)
    at /var/www/html/plugins/alexaapiv2/resources/alexaapi_test.js:601:8
    at Layer.handle [as handle_request] (/var/www/html/plugins/alexaapiv2/resources/node_modules/express/lib/router/layer.js:95:5)
    at next (/var/www/html/plugins/alexaapiv2/resources/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/var/www/html/plugins/alexaapiv2/resources/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/var/www/html/plugins/alexaapiv2/resources/node_modules/express/lib/router/layer.js:95:5)
    at /var/www/html/plugins/alexaapiv2/resources/node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/var/www/html/plugins/alexaapiv2/resources/node_modules/express/lib/router/index.js:346:12)
```

Is that enough?

since midday we have no longer been able to retrieve history, and this does not seem to impact us, same problems with another plugin using your library in the latest version.

**Comment by Apollon77** [comment]
In fact check the error ...it seems that the library thinks that there is still activity update in progress but you trigger another one, so the library prevents this. Hard to say about the reason without mroe details ... try to restart.

In fact till now no other probems were reported

**Comment by skillix** [comment]
thank you for the feedback one it works again (without doing anything since this morning) for me I remain stuck we continue to search

**Comment by skillix** [comment]
yes I saw afterwards and I think that the difference in behavior was due to loadbalancing on the Amazon servers
