### ISSUE TITLE
Problems using login credentials

### ISSUE THREAD

**Issue by Gansgar** [Apollon77/alexa-remote#61]
I would like my script to automatically login using the login credentials provided in the script. 

This is my log
```Alexa-Remote: Use as User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
Alexa-Remote: Use as Login-Amazon-URL: amazon.de
Alexa-Remote: Use as Base-URL: layla.amazon.de
Alexa-Remote: No cookie given, generate one
Alexa-Cookie: Use as Login-Amazon-URL: amazon.de
Alexa-Cookie: Use as User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
Alexa-Cookie: Use as Accept-Language: en-US,en;q=0.9,de;q=0.8
Alexa-Cookie: Proxy mode disabled
Alexa-Cookie: Step 1: get first cookie and authentication redirect
Alexa-Cookie: Sending Request with {"host":"alexa.amazon.de","path":"","method":"GET","headers":{"DNT":"1","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36","Accept-Language":"en-US,en;q=0.9,de;q=0.8","Connection":"keep-alive","Accept":"*/*"}}
Alexa-Cookie: Response (302) - Redirect to https://www.amazon.de/ap/signin?showRmrMe=1&openid.return_to=https%3A%2F%2Falexa.amazon.de%2F&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_dp_project_dee_de&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&
Alexa-Cookie: Sending Request with {"host":"www.amazon.de","path":"/ap/signin?showRmrMe=1&openid.return_to=https%3A%2F%2Falexa.amazon.de%2F&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_dp_project_dee_de&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&","method":"GET","headers":{"DNT":"1","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36","Accept-Language":"en-US,en;q=0.9,de;q=0.8","Connection":"keep-alive","Accept":"*/*","Cookie":""},"body":""}
Alexa-Cookie: Response (200)
Alexa-Cookie: Add Cookie session-id = 257-6882699-5178908
Alexa-Cookie: Add Cookie session-id-time = 2208727619l
Alexa-Cookie: Step 2: login empty to generate session
Alexa-Cookie: Sending Request with {"host":"www.amazon.de","path":"/ap/signin","method":"POST","headers":{"DNT":"1","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36","Accept-Language":"en-US,en;q=0.9,de;q=0.8","Connection":"keep-alive","Content-Type":"application/x-www-form-urlencoded","Referer":"https://www.amazon.de/ap/signin?showRmrMe=1&openid.return_to=https%3A%2F%2Falexa.amazon.de%2F&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_dp_project_dee_de&openid.mode=checkid_setup&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&","Cookie":"session-id=257-6882699-5178908; session-id-time=2208727619l","Accept":"*/*"},"gzip":true,"body":""}
Alexa-Cookie: Response (404)
Alexa-Cookie: Add Cookie ubid-acbde = 257-2645367-6834169
Alexa-Cookie: Step 3: login with filled form, referer contains session id
Alexa-Cookie: Sending Request with {"host":"www.amazon.de","path":"/ap/signin","method":"POST","headers":{"DNT":"1","Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36","Accept-Language":"en-US,en;q=0.9,de;q=0.8","Connection":"keep-alive","Content-Type":"application/x-www-form-urlencoded","Referer":"https://www.amazon.de/ap/signin/257-6882699-5178908","Cookie":"session-id=257-6882699-5178908; session-id-time=2208727619l; ubid-acbde=257-2645367-6834169","Accept":"*/*"},"gzip":true,"body":"email=MYMAIL%2Bdev%40gmail.com&password=PASSWORD"}
Alexa-Cookie: Response (404)
Alexa-Remote: Error from retrieving cookies
Error: Login unsuccessfull. Please check credentials.
    at request (/opt/alexa-timer-on-lametric-time/node_modules/alexa-cookie2/alexa-cookie.js:351:50)
    at IncomingMessage.res.on (/opt/alexa-timer-on-lametric-time/node_modules/alexa-cookie2/alexa-cookie.js:111:33)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)```

**Comment by Gansgar** [comment]
This seems to be a new problem: https://github.com/Apollon77/ioBroker.alexa2/issues/243

How can we apply the "login with proxy once" method using this library?

**Comment by Apollon77** [comment]
Do not try the "Username/password" login stuff anymore ... Amazon build too many countermeasures and protection. Thas why it was removed kind of and replaced by "login once, get tokens and refresh them" exaactly as the Alexa App is doing it.

Some infos and example on how to use the new stuff --> https://github.com/Apollon77/alexa-cookie

**Comment by Gansgar** [comment]
Thanks. But is this implemented in this library or do I need to write my own implementation?

Because as for now, I'm unable to automatically retrieve the cookie and need to do proxy login every time I use the node js script.

**Comment by Apollon77** [comment]
The library only detects missing credentials and provides callbacks with the data. You need to take care of fetching, storing and providing these data (formerRegistrationData and such) on next usage.

**Comment by Gansgar** [comment]
Ah oke. Thanks. I'll do this in another time. But thanks tip.
